### ISSUE TITLE
IContainer.Resolve method - Return a component instance by the key.

### ISSUE THREAD

**Issue by moodmosaic** [davybrion/Agatha#2]
It would be good if we could add methods to the IContainer interface for returning a component instance by key:

TComponent Resolve<TComponent>(String key);

Then we could just write:

ConcreteA a = IoC.Container.Resolve<SomeBaseClass>("KeyA");
ConcreteB b = IoC.Container.Resolve<SomeBaseClass>("KeyB");

(The above is not possible for now).

**Comment by davybrion** [comment]
If all containers support it by now, then yeah, we could add it

but i'm not sure whether we should do it, because it's not something that is (or will be) used by Agatha directly... it's a container feature that you're likely only going to use in your own application code so you could just keep using it through your own reference to the actual container (the one you pass into the configuration objects at application initialization time

thoughts?

**Comment by moodmosaic** [comment]
Here is another point of view:

From application code one might use the methods from the Agatha.Common.InversionOfControl.IoC class in order to use the application's container as a service locator (without having to expose the actual container anywhere else than the bootstrapper class). 

That way the caller, when/if trying to get a component instance via service location he just uses the methods from the IoC class.

Now, I do believe that people using the library already use the IoC class for their service locator needs (if any).
Of course one can avoid returning a component instance by key and use a factory instead. (But factories never perform good specially when doing a lot with the container because most of the times a factory object is created, adding overhead and pressure).

Adding this overload to the IoC class won't hurt actually, and it drastically simplifies everything else that has to be done in order to achieve this with other ways.

In my local clone I added this method, implemented on all container adapters and I only need to find out how it's done in Spring :D

**Comment by davybrion** [comment]
if you get it working for spring as well, i'll gladly merge the pull request :)

**Comment by moodmosaic** [comment]
I'm done with Spring. I would like to add some unit-tests. Should I add them at ConfigurationTests section?

**Comment by davybrion** [comment]
yeah, you can add tests to the ConfigurationTests but please do so in the same manner as it's done for the tests about known-component resolving: put it in the generic test fixture so that the tests are inherited by each specific derived container fixture

as for the Release method: it really can't throw an exception because agatha calls that method after having handled a request.  if a container doesn't implement it (and most don't), it needs to be a silent no-op

**Comment by moodmosaic** [comment]
I look now the ComponentResolving<TContainer> fixtures. To add tests for that feature I have to register some components by specifying a key. Since this is not offered by the IContainer interface (and I don't think that it should get added) it goes out of scope of the ComponentResolving<TContainer> fixtures.

In order to keep it simple, I can make a pull request without the tests for that feature (if code is not covered completely by tests that could be just fine).

**Comment by davybrion** [comment]
i'd rather have those specific container implementations all tested though... you could test the feature by registering the components by key through the actual container instance, so we don't need to introduce a new register method to IContainer

**Comment by moodmosaic** [comment]
Each actual container instance though is not accessible through tests. In fact, the container assemblies are not even referenced on the Tests project.

**Comment by davybrion** [comment]
that's because we haven't needed to reference them directly... we only reference the Agatha-specific container implementations which in turn reference the actual assemblies.  There's no problem at all with referencing them directly and using the actual container implementation to test this.

**Comment by moodmosaic** [comment]
ok, unit tests on their way next hour

**Comment by moodmosaic** [comment]
all tests (passing) can be found on ComponentResolvingByKey.cs (on pull request). I also made a question on stackoverflow about Ninject's ability to resolve a component instance by key.

**Comment by davybrion** [comment]
thx!
i'll merge your pull request tonight
